### ISSUE TITLE
Console problem 

### ISSUE THREAD

**Issue by erfan132** [OxideMod/Oxide.Hurtworld#46]
hey man
 server console closed when server running its like that server console is hide  (  this problem made in last version of oxide )
 https://ufile.io/3dmgj

**Comment by lukespragg** [comment]
You do not have Oxide installed.

**Comment by erfan132** [comment]
its installed

**Comment by lukespragg** [comment]
Since you do not see a console, it isn't, as Oxide provides that console.

**Comment by erfan132** [comment]
when i use latter version of oxide my console work well 
hurtworld server version 3.8.9

**Comment by lukespragg** [comment]
I'd suggest looking for the OXIDE.txt file from the build you downloaded before, it has information that should be read.

**Comment by erfan132** [comment]
i dont found this file

**Comment by lukespragg** [comment]
Where are you downloading the build from?

**Comment by lukespragg** [comment]
There's no reason why that wouldn't work, others are using it just fine. I'd suggest checking your logs for errors and make sure your server is fully updated to the brand for that build; in this case, the main branch, not the itemv2 branch.

**Comment by erfan132** [comment]
my probelm fixed 
where is fps and players count of server in new version of oxide 
omg commands not answering

**Comment by erfan132** [comment]
https://ufile.io/rl4le
